### ISSUE TITLE
llvm-dg-dump fail with assertion 'successors.size() == 1' 

### ISSUE THREAD

**Issue by ivanpostolski** [mchalupa/dg#311] opened 2020-03-06 02:06 UTC
Hello 

I'm trying to run a dg-dump over an old version of grep (I've attached to this post), I'm running the following command lines

`clang-6.0 -g -emit-llvm -c -o grep.bc grep.c`
`llvm-dg-dump grep.bc` 

And the message that I'm getting is:

```
Warning: Empty PHI
PSNodeType::PHI with ID 345
  - operands: []
Warning: Empty PHI
PSNodeType::PHI with ID 346
  - operands: []
IntToPtr with constant:   <badref> = inttoptr i64 -1 to i8*
llvm-dg-dump: /home/ivan/Documents/phd/tools/dg-6.0/include/dg/analysis/SubgraphNode.h:181: NodeT* dg::analysis::SubgraphNode<NodeT>::getSingleSuccessor() const [with NodeT = dg::analysis::pta::PSNode]: Assertion `successors.size() == 1' failed.

```

Any help is much appreciated!

[old-grep.zip](https://github.com/mchalupa/dg/files/4296096/old-grep.zip)

**Comment by mchalupa** [comment] 2020-03-09 15:16
Could you, please, try checking out the `sdg-1.0.0` branch and try on that branch?

**Comment by mchalupa** [comment] 2020-03-16 13:04
I guess this could be a duplicate of https://github.com/mchalupa/dg/issues/302 ?

**Comment by mchalupa** [comment] 2020-07-21 20:03
Since there is no activity here, I'm closing it as a duplicate of #302. Re-open if needed.

**Closed by mchalupa** 2020-07-21 20:03 UTC
Labels: bug
