### ISSUE TITLE
loop condition is sliced away

### ISSUE THREAD

**Issue by anahitH** [mchalupa/dg#134] opened 2017-02-03 12:39 UTC
Hi, 

I noticed that dg slices away part of while loop condition expression and its (while) empty body block.

Consider following while loop:

    unsigned n = 0;
    scanf("%d", &n);
    int i = 0;
    int sum = 0;
    while (++i < n - 3) {}
    sum += i;
    write_sum(sum)

Slicing criterion is write_sum. dg slices away the comparison of i and (n - 3) in while condition, as well as the empty body block of the loop. Although slicing criterion depends on both. 

On the other hand, if considering code snippet doing the same thing, by using for instead of while, dg keeps comparison part. Note empty body block is again sliced, but in this case it does not effect the result, as the incrementing block is there and loop continues normally.

    unsigned n = 0;
    scanf("%d", &n);
    int i = 0;
    int sum = 0;
    for (; i < n - 3; ++i) { }
    sum += i;
    write_sum(sum);

Could you please explain whether this is an issue, or unimplemented feature or maybe it is exactly the way you thought to be.

Thanks.

**Comment by mchalupa** [comment] 2017-02-06 12:38
Hi,

The problem here is in the algorithm for computing control dependencies. It does not handle correctly the cases, where the loop looks like this (which is the case of your program):
```
  |
  v
  B1<---> B2
  |
  v
  B3                   
```
Its not a bug in the algorithm, nor in the slicer, but it is a result of wrong assumptions  that the algorithm makes about programs (the algorithm is from 80's, so no wonder). Fix for this would be to implement better algorithm. We currently have an experimental support for different algorithm, you can try it with `-cd-alg=ce`. But be aware that this different algorithm is not debugged or used in practice.

**Comment by mchalupa** [comment] 2019-05-28 08:20
There is a new CD algorithm that should handle these cases. You can run it using `-cd-alg=ntscd`

Cheers

**Closed by mchalupa** 2019-05-28 08:20 UTC
